language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew
  -
before_deploy:
  - zip -r first-springboot-project *
  - mkdir -p deploy
  - mv first-springboot-project.zip deploy/first-springboot-project.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: first-springboot-project-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: first-springboot-project-build
    key: first-springboot-project.zip
    bundle_type: zip
    application: first-springboot-project
    deployment_group: first-springboot-project-group
    region: ap-northest-2
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - pakrjun@gmail.com